export const GITHUB_REPOSITORY_REQUEST = 'GITHUB_REPOSITORY_REQUEST'
export const GITHUB_REPOSITORY_SUCCESS = 'GITHUB_REPOSITORY_SUCCESS'
export const GITHUB_REPOSITORY_FAILURE = 'GITHUB_REPOSITORY_FAILURE'
export const GITHUB_REPOSITORY_CLEAR = 'GITHUB_REPOSITORY_CLEAR'
