version: 2

jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:8.4.0
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: install
          command: yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: lint
          command: yarn lint
      - run:
          name: test
          command: yarn test
      - run:
          name: build
          command: yarn build
      - persist_to_workspace:
          root: ~/project
          paths:
            - dist/*

  # - AWS_ACCOUNT_ID
  # - AWS_REGION
  # - CIRCLE_PROJECT_REPONAME (default)
  # - CIRCLE_SHA1 (default)
  registry:
    working_directory: ~/project
    machine:
      enabled: true
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: registry
          command: ./script/registry.sh

  # - AWS_ACCOUNT_ID
  # - AWS_REGION
  # - EC2_USERNAME (DEV/PROD)
  # - EC2_HOST (DEV/PROD)
  # - HOST_PORT (DEV/PROD)
  # - CIRCLE_PROJECT_REPONAME (default)
  deploy-dev:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: deploy development
          command: ./script/deploy.sh ${EC2_USERNAME_DEV} ${EC2_HOST_DEV} ${HTTP_PORT_DEV}
  deploy-prod:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: deploy production
          command: ./script/deploy.sh ${EC2_USERNAME_PROD} ${EC2_HOST_PROD} ${HTTP_PORT_PROD}

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - registry:
          requires:
            - build
      # only master branch
      - deploy-dev:
          requires:
            - registry
          filters:
            tags:
              ignore: /.*/
            branches:
              only: master
      # only tags
      - deploy-prod:
          requires:
            - registry
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
