version: 2

jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:8.4.0
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: install
          command: yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: lint
          command: yarn lint
      - run:
          name: test
          command: yarn test

  deploy:
    working_directory: ~/project
      docker:
        - image: circleci/node:8.4.0
      - run:
          name: deploy development
          command: |
            echo "TODO deploy DEV"
            ./script/deploy.sh

  deploy:
    working_directory: ~/project
      docker:
        - image: circleci/node:8.4.0
      - run:
          name: deploy production
          command: |
            echo "TODO deploy PROD"
            ./script/deploy.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            tags:
              ignore: /.*/
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
