version: 2

jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:8.4.0
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: install
          command: yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: lint
          command: yarn lint
      - run:
          name: test
          command: yarn test
      - run:
          name: build
          command: yarn build

  # - AWS_ACCOUNT_ID
  # - AWS_REGION
  # - CIRCLE_PROJECT_REPONAME (default)
  # - CIRCLE_WORKING_DIRECTORY (default)
  # - CIRCLE_SHA1 (default)
  registry:
    machine:
      enabled: true
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: registry
          command: ./script/registry.sh

  deploy-dev:
    machine:
      enabled: true
    steps:
      - run:
          name: deploy development
          command: ./script/deploy.sh
  deploy-prod:
    machine:
      enabled: true
    steps:
      - run:
          name: deploy production
          command: ./script/deploy.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - registry:
          requires:
            - build
      # only master branch
      - deploy-dev:
          requires:
            - registry
          filters:
            tags:
              ignore: /.*/
            branches:
              only: master
      # only tags
      - deploy-prod:
          requires:
            - registry
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
