version: 2

jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:8.4.0
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: install
          command: yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: lint
          command: yarn lint
      - run:
          name: test
          command: yarn test

  registry:
    working_directory: ~/project
    docker:
      - image: circleci/node:8.4.0
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: build
          command: yarn build
      - run:
          name: registry
          command: echo REGISTRY

  deploy:
    working_directory: ~/project
    docker:
      - image: circleci/node:8.4.0
    steps:
      - checkout
      - run:
          name: example
          command: echo DEPLOY

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - registry:
          requires:
            - build
      - deploy:
          requires:
            - registry
